### ISSUE TITLE
【商品管理ページ】  migration作成

### ISSUE THREAD

**Issue by Apro-yuto** [Apro-yuto/highlight#9]

**Comment by masato5579** [comment]
## テーブル内容（スプレッドシート）
https://docs.google.com/spreadsheets/d/17wQv7memqseOFo_jEP2_aRBwoci0Y6xNRZthF7ptUWE/edit#gid=1966123753

## 作成するmigration一覧
- [ ] items
- [ ] brands
- [ ] categories
- [ ] colors
- [ ] color_item
- [ ] labels
- [ ] shops
- [ ] statuses
- [ ] suppliers
